# Generated by Django 4.2 on 2025-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_account_locked_until_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_verification_tokens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
