# Generated by Django 4.2 on 2025-04-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user__verification_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_verification_tokens',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_tokens',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
