# Generated by Django 4.2 on 2025-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_user__verification_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable the scheduled sync')),
                ('direction', models.CharField(choices=[('to-django', 'From Supabase to Django'), ('to-supabase', 'From Django to Supabase'), ('both', 'Bidirectional')], default='to-django', help_text='Direction of the synchronization', max_length=15)),
                ('frequency', models.CharField(choices=[('hourly', 'Every Hour'), ('daily', 'Every Day'), ('weekly', 'Every Week')], default='daily', help_text='How often to run the synchronization', max_length=10)),
                ('force_update', models.BooleanField(default=False, help_text='Force update even if users already exist')),
                ('last_run', models.DateTimeField(blank=True, help_text='When the sync was last executed', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='When the sync is scheduled to run next', null=True)),
                ('last_status', models.TextField(blank=True, help_text='Status of the last sync operation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Sync Schedule',
                'verbose_name_plural': 'User Sync Schedules',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='supabase_id',
            field=models.CharField(blank=True, db_index=True, help_text='User ID in Supabase', max_length=255, null=True),
        ),
    ]
