# Generated by Django 4.2 on 2025-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_integration_chatbot_app', '0002_conversation_taskcreationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
