# Generated by Django 4.2 on 2025-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_integration_chatbot_app', '0003_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='Conversation', max_length=255),
        ),
    ]
