# Generated by Django 4.2 on 2025-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_integration_chatbot_app', '0004_conversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='metadata',
            field=models.TextField(blank=True, help_text='JSON data for conversation state tracking', null=True),
        ),
    ]
