# Generated by Django 4.2 on 2025-05-01 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_integration_chatbot_app', '0005_conversation_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='metadata',
        ),
        migrations.AddField(
            model_name='taskcreationrequest',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_creations', to='chatbot_integration_chatbot_app.conversation'),
        ),
        migrations.AddField(
            model_name='taskcreationrequest',
            name='current_step',
            field=models.CharField(choices=[('title', 'Title'), ('due_date', 'Due Date'), ('priority', 'Priority'), ('description', 'Description'), ('done', 'Done')], default='title', max_length=20),
        ),
        migrations.AddField(
            model_name='taskcreationrequest',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskcreationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taskcreationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_task_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskcreationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskcreationrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='taskcreationrequest',
            unique_together={('user', 'conversation', 'status')},
        ),
        migrations.RemoveField(
            model_name='taskcreationrequest',
            name='message',
        ),
    ]
