# Generated by Django 4.2 on 2025-05-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_integration_chatbot_app', '0006_remove_conversation_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreationrequest',
            name='created_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
