# Generated by Django 4.2 on 2025-05-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_integration_chatbot_app', '0007_alter_taskcreationrequest_created_task_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcreationrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='taskcreationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'conversation'), name='unique_active_task_request'),
        ),
    ]
