# Generated by Django 4.2 on 2025-05-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_integration_chatbot_app', '0008_alter_taskcreationrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskcreationrequest',
            name='unique_active_task_request',
        ),
    ]
